{
 "title": "Metrics (from Netbox Devices)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "### Metrics\nThe two panels below split metrics by the `device_role` label, added from the Netbox Exporter. This is useful for displaying metrics (and various aggregates) based on the device role.\n"
   }
  },
  {
   "title": "Edge Routers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "interface_bitrate_rx:30s{device_role=\"edge-router\"}",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "interface_bitrate_tx:30s{device_role=\"edge-router\"}",
     "legendFormat": "{{device}} TX"
    }
   ]
  },
  {
   "title": "PE Routers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "interface_bitrate_rx:30s{device_role=\"pe-router\"}",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "interface_bitrate_tx:30s{device_role=\"pe-router\"}",
     "legendFormat": "{{device}} TX"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "### Connected Device\nThese two panel show interface metrics for the `edge1` router, only for interfaces connected to `pe-router` devices. This is all dynamic, based on netbox data. It doesn't matter what you change or re-patch, as long as Netbox indicates the Source of Truth, this panel will update accordingly.\nThis is useful for filtering on uplink/downlink interfaces, OOB interfaces, transit interfaces etc."
   }
  },
  {
   "title": "Edge1 --> PE Routers Only",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "interface_bitrate_rx:30s{device=\"edge1.tdr.id.au\", connected_device=~\"pe.*\"}",
     "legendFormat": "{{device}} RX"
    },
    {
     "expr": "interface_bitrate_tx:30s{device=\"edge1.tdr.id.au\", connected_device=~\"pe.*\"}",
     "legendFormat": "{{device}} TX"
    }
   ]
  }
 ]
}